FROM ubuntu:focal

LABEL maintainer="Mariya Dyakova"

ARG USER_ID
ARG GROUP_ID

# ENV  USER=$USER_ID

RUN apt-get update \
    &&  apt-get install -y wget \
    git \
    unzip \
    make \
    g++

RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.63.0/source/boost_1_63_0.zip \
    && unzip boost_1_63_0.zip \
    && mv boost_1_63_0 /usr/local/bin \
    && rm boost_1_63_0.zip

RUN git clone https://github.com/facebookresearch/Starspace.git \
    && cd Starspace \
    && make

RUN addgroup --gid $GROUP_ID user1
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user1
USER user1

RUN mkdir -p /home/user1/starspace
    
WORKDIR /home/user1/starspace

CMD /Starspace/starspace train -trainFile ./uci_train_starspace_formatted.txt -model modelSaveFile
