FROM ubuntu:focal

LABEL maintainer="Mariya Dyakova"

RUN apt-get update \
    &&  apt-get install -y wget \
    git \
    unzip \
    make \
    g++

RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.63.0/source/boost_1_63_0.zip \
    && unzip boost_1_63_0.zip \
    && mv boost_1_63_0 /usr/local/bin \
    && rm boost_1_63_0.zip

RUN git clone https://github.com/facebookresearch/Starspace.git \
    && cd Starspace \
    && make

# create a user to launch the application
RUN groupadd --gid 5000 newuser \
    && useradd --home-dir /home/newuser --create-home --uid 5000 \
        --gid 5000 --shell /bin/sh --skel /dev/null newuser



RUN mkdir /opt/starspace \
    && chmod -R 0775 /opt/starspace \
    && chown -R newuser:newuser /opt/starspace \
    && chmod g+s /opt/starspace/
    
WORKDIR /opt/starspace

USER newuser

CMD /Starspace/starspace train -trainFile ./uci_train_starspace_formatted.txt -model modelSaveFile
